### PR TITLE
Tabs to spaces -- 4 or 8 depending on what each file was written with the idea of

### PR DESCRIPTION
**Pull request by native-api**
The sources currently use a mix of tabs and spaces for indentation. Moreover, some were written with the idea of tab=8 while others with tab=4, so whatever the editor tab setting is, some files look misaligned.

These files were written with tabs with the idea of tab-8 (the rest are tab-4 or don't use tabs):
* `README`, `Changelog*`, `changes`
* sources in `generic/`, `compat/`, `macosx/`, `unix/`, `win/`
    * except: `configure.ac`, `tcl.m4`. XML files, project files

Tests in `tests/` are tab-4 and tab-8 about 50/50
* the following files have inline tabs as test data: `option.file*` (didn't touch them), `bind.test`.

`library/` also has both cases of tab-8 and tab-4.

### CODE REVIEW

**Comment by fvogelnew1** [comment]
TIP 247 describes the engineering manual or Tcl/Tk.

http://core.tcl.tk/tips/doc/trunk/tip/247.md

Both tabs and spaces are allowed in the source code:

"Indents are 4 Spaces
Each level of indentation should be four spaces. There are ways to set 4-space indents in all editors that I know of. Be sure that your editor really uses four spaces for the indent, rather than just displaying tabs as four spaces wide; if you use the latter approach then the indents will appear eight spaces wide in other editors.
If you use tabs, they must be to 8-space indents."

**Comment by native-api** [comment]
> TIP 247 describes the engineering manual or Tcl/Tk.
> http://core.tcl.tk/tips/doc/trunk/tip/247.md

How does this combine with https://www.tcl.tk/doc/styleGuide.pdf and http://wiki.tcl.tk/708 ? (1st in Google on "tcl code style"; the latter refers to https://core.tcl.tk/tips/doc/trunk/tip/352.md which is newer than the above TIP.)
They say just "four spaces", nothing about tabs.

Besides, that TIP is marked as "draft" and "vote pending", it looks like it was never enacted.

In any case, the problem is that the style in files is inconsistent -- whichever convention is the current one, some files are breaking it.

**Comment by fvogelnew1** [comment]
I have brought this to the attention of the Tcl core list, see:

    http://code.activestate.com/lists/tcl-core/20132/

**Comment by native-api** [comment]
In the meanwhile, it looks like I wasn't able to fully bring my point across, either.

The primary motivation for this PR is that currently some files are written with the idea that tab=8 spaces but some with the idea that tab=4 spaces.
So, _whichever tab setting I use in the editor, some files will look misaligned and it's nigh-impossible to work with them._

For example, it's impossible to edit a file with the intended tab size other than your editor's one without breaking its alignment.

I'm not a fan of changes for the sake of changes, either, but here, this is not the case AFAICS.
The previous paragraph is a real problem, and being unable to work with half of the codebase is much more serious than having a single noise commit in history. Isn't it?

I'm fine with reducing the PR to fix just files with tab-4 or tab-8. As long as the above problem is solved, it's good.

**Comment by fvogelnew1** [comment]
I have understood what you're pointing out. However after many years working in the source code of Tk, I never encountered the issue you describe I think. My editor tab settings is tab-8, the code displays nicely, and I mostly use spaces anyway.

**Comment by native-api** [comment]
(Then judging "right"/"wrong" below, I take into account that continuation lines use double indent.)

The following files are written with the idea of tab-4, so when viewing with editor set to tab=8, indentations look wrong and/or inconsistent (set your editor to show whitespace to see where tabs contribute).

```
tests/embed.test
tests/entry.test
tests/event.test
tests/event.test
tests/geometry.test
tests/imgBmap.test
tests/main.test
tests/option.test
tests/panedwindow.test
tests/scale.test
tests/spinbox.test
tests/text.test
win/Makefile.in
win/configure
win/stubs.c
```

These files appear to use a mix of tab-8 and tab-4, so with any setting, some indents look wrong:

```
tests/imgListFormat.test
tests/raise.test
tests/xmfbox.test
unix/configure
```

The following files use tabs exclusively, so with tab=8, they look double-indented:

```
.project
macosx/Tk-Info.plist.in
macosx/Tk.xcode/default.pbxuser
macosx/Tk.xcode/project.pbxproj
macosx/Tk.xcodeproj/default.pbxuser
macosx/Tk.xcodeproj/project.pbxproj
macosx/Wish-Info.plist.in
macosx/Wish.sdef
```

(Finally, found a few more files that have embedded tabs as data:)
```
tests/imgPPM.test
unix/configure
win/configure
```

**Comment by fvogelnew1** [comment]
Yes, I definitely see what you mean, and thank you for the extensive status.

However I'm afraid I (and others on tcl-core list as well) really view such a whitespace-only change as too noisy compared to the added value it brings. I think we should "fix" these whitespace issues when changing the impacted files for reasons such as code improvements/changes or bugfixes.

**Comment by dkfellows** [comment]
The style guide applies to Tcl code. The engineering manual applies to C code. Our general style has changed _slightly_ since they were written (e.g., we now assume that we're build with quite a bit more modern version of C) but they are still considered to be things that should be followed in spirit.

If we ever bother get CI integration working better, I'm aware of some enforcement tools (that use Tcl!) which would let us get much stricter. In the meantime, pure whitespace changes are _highly_ unpopular as they make tools like `git blame` useless.

**Comment by native-api** [comment]
@fvogelnew1, you didn't mention the conflicting tabs sizes in the list thread, so it seems to me you didn't really get feedback on _that_ point.
They only stated that whitespace changes are useless if there's no real problem to solve (["people concerned about white space in source code are trying to make something out of nothing"](http://code.activestate.com/lists/tcl-core/20136/)).

I've had actual trouble seeing code structure when browsing through it because of unusual and inconsistent indentation, so there is a real problem to solve -- if you're interested in anyone except a few select people to be able to work with the code, that is.

* Inconsistent tab size is the bigger problem -- no-one at all is able to work with the entire codebase.
* Using tabs for indentation and assuming tab=8 is the lesser problem -- no-one with default settings is able to work with most of the codebase.
Like it or not, "tab=4, replace with space" is the standard setting in editors and IDEs now (long story short, it proved to be the optimal choice overall as the default). One isn't going to reconfigure that each time they need to switch between tcl/tk code and something else.

**Comment by native-api** [comment]
@dkfellows, I actually have some firsthand experience: Python codebase used to have the same problem.

They fixed it [with a single commit](https://github.com/python/cpython/commit/c83ea137d7e717f764e2f31fc2544f522de7d857) to minimize the impact, and are enforcing "spaces only" since as part of code reviews (which are required for pull requests anyway).
(This is why I opted to fix everything at once here, too -- as the first suggested option, at least.)

I've hit that commit several times when blaiming the source, but since there's only one of it, this hasn't been noticeably slowing me down. (And for scripting purposes, you cannot assume that you'll get the entire rationale for a line on the first `blame` anyway 'cuz a line may have been changed several times.) As more commits are added on top of it, it becomes ever less and less of a issue.

---

That said, in Git, it's possible to rewrite history. So I could go all the way back to original commits and fix tabs right there (across branches, too), no "noise commits" whatsoever.  After that though, you'll have to regenerate your repository from the resulting branches: essentially, rename the existing branches, import fixed ones, then delete the old ones.

**Comment by native-api** [comment]
> The style guide applies to Tcl code. The engineering manual applies to C code. Our general style has changed slightly since they were written (e.g., we now assume that we're build with quite a bit more modern version of C) but they are still considered to be things that should be followed in spirit.

I'm okay with a distinction and whatever changes. The problem is one has no way to learn all this unless they are already someone "in the know".

Maybe you could consider clarifying the TIPs' statuses and making them refer to one another? (E.g. like https://www.python.org/dev/peps/pep-0007/ and https://www.python.org/dev/peps/pep-0008/ do.)

Multiple code styles for the same project are anything but standard practice (or best practice, specifically because of inevitable conflicts down the road).

**Comment by native-api** [comment]
Any update with this?

If the Tcl/Tk project isn't interested in making in easy for external parties to contribute (for which a readable codebase is a prerequisite), just explicitly say so and close the ticket.

Then I, and anyone else who also has a problem with readability, will know that contributions towards this goal are not welcome here and we should go contribute somewhere else if the inconvenience is too much for us.

**Comment by mpcjanssen** [comment]
First of all I think the different types of indentation and their effect on readability are greatly exaggerated for languages like Tcl or C.

So let me add my own anectdata. I find commits which make cosmetic changes only very annoying. A single big change is one thing but several cosmetic only changes make `git blame` pretty much useless.
I much prefer cosmetic changes and consistency to be restored while doing functional changes as well.

Also the premise that not accepting this pull request means the maintainers don't care about readability is totally over the top. It just means the maintainers don't value consistency above all else.

Finally, submitting a pull request is no guarantee it gets merged, any expectation otherwise is just a case of entitlement IMO.

**Comment by mpcjanssen** [comment]
Also re: rewriting history: Tcl uses fossil as the core DVCS (this repo is a mirror). Fossil does not allow rewriting history (by design)

**Comment by dkfellows** [comment]
We have discussed your PR, and rejected it for offering too little value for downstream users.

**Comment by native-api** [comment]
Hmm... the only discussion I could find is the http://code.activestate.com/lists/tcl-core/20402/ thread which doesn't mention any users whatsoever. Whatever. This ticket has enough feedback to show that you're not interested (or at least say so).

At least I have a clear answer for posterity so they can decide if they really want to get involved.

**Pull request closed without merging**
