### PR TITLE
Retrieve -postoffset value from correct style

### PR DESCRIPTION
**Pull request by dpanda**
The actual `combobox.tcl` implementation reads the `-postoffset` value from the `TCombobox` style, instead of reading it from the style actually applied to the widget.

It is therefore impossible to customize this property in derived styles. This commit fixes it.

### CODE REVIEW

**Comment by fvogelnew1** [comment]
The proposed fix was merged in 2016, see the ticket at Tk repository:
https://core.tcl.tk/tk/tktview?name=f60c54bec6

Thanks!

**Comment by dkfellows** [comment]
Only a “project member” with sufficient privileges can do Closing. Who is a member here is rather messed up. (@andreas-kupries might be able to fix this as I can see him [listed](https://github.com/orgs/tcltk/people), but I sure can't…)

**Comment by sebres** [comment]
I can... thus closed as merged in fossil. Thx.

**Comment by sebres** [comment]
*just as loud thoughts...*
@fvogelnew1 François I'm pretty sure you'll get expected privileges if you ask the repo owners (@andreas-kupries, @das, @jeff-hobbs, @patthoyts)...

**Pull request closed without merging**
